version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: test_fastapi
    container_name: test_fastapi
    privileged: true
    expose:
      - "8000"
    ports:
      - "8000:8000"
